# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 39c4590
_src_path: https://gitlab.com/gemseo/dev/copier-gemseo
author_email: contact@gemseo.org
author_name: François Gallard
gemseo_min_version: '5'
package_is_a_gemseo_plugin: true
project_is_open_source: true
project_name: gemseo-petsc
project_name_suffix: petsc
project_slug: gemseo_petsc
short_description: PETSc GEMSEO interface.
use_gemseo_develop: true
