include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

test:
  image: registry.gitlab.com/gemseo/dev/gemseo-petsc/multi-python-miniforge
  parallel:
    matrix:
      - TAG:
          - docker
        TOX_ENV_NAME:
          - py38-coverage
          - py39-coverage
          - py310-coverage
