default:
  image: continuumio/miniconda3:4.9.2

# Stages executed sequentially until a job fails.
stages:
  - check
  - tests

variables:
  TOX_CONDA_VERSION: "0.9.2"
  CODECOV_VERSION: "2.1.12"

workflow:
  # Prevent duplicated pipelines,
  # see https://docs.gitlab.com/14.3/ee/ci/yaml/index.html#switch-between-branch-pipelines-and-merge-request-pipelines.
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

# Base job template.
.base:
  interruptible: true
  script:
    # Run a tox env named after a job name.
    - tox -e $TOX_ENV_NAME

# Specific settings for linux jobs.
.linux:
  tags:
    - gemseo-docker
  variables:
    # Caches on the CI runner host.
    CONDA_PKGS_DIRS: "/opt/gitlab-runner-cache/conda"
    PIP_CACHE_DIR: "/opt/gitlab-runner-cache/pip"
  before_script:
    - python -m venv .tox-venv
    - source .tox-venv/bin/activate
    - python -m pip install tox-conda==$TOX_CONDA_VERSION
    - python -m pip install codecov==$CODECOV_VERSION

# Specific settings for windows jobs.
.windows:
  tags:
    - gemseo-windows-server-2012
  variables:
    # Caches on the CI runner host.
    PIP_CACHE_DIR: "C:\\pip"

# Jobs for the check stage.
check:
  extends:
    - .base
    - .linux
  stage: check
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    # Pass the cache locations through the tox env.
    TOX_TESTENV_PASSENV: PIP_CACHE_DIR PRE_COMMIT_HOME
    TOX_ENV_NAME: check

# Tests stage.

# Base tests job, common to all the tests jobs.
.tests:
  extends: .base
  stage: tests
  variables:
    COVERAGE_FILE: coverage.xml
    # The junitxml is for showing the number of tests if gitlab UI.
    PYTEST_ADDOPTS: --junitxml=report.xml
    TOX_TESTENV_PASSENV: PYTEST_ADDOPTS
  artifacts:
    # Send the artifacts even on job failure.
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: $COVERAGE_FILE
  # To get the total coverage shown in gitlab UI.
  coverage: '/^TOTAL.+?(\d+\%)$/'
  rules:
    # Only run a test job when the following files have changed.
    - changes:
      - src/**/*.*
      - tests/**/*.*
      - requirements/test.txt
      - setup.cfg
      - tox.ini
      - .gitlab-ci.yml
  after_script:
    - codecov -t $CODECOV_TOKEN -f $COVERAGE_FILE --required

# Common settings for windows tests jobs.
.tests-windows:
  extends:
    - .tests
    - .windows

# Common settings for linux tests jobs.
.tests-linux:
  extends:
    - .tests
    - .linux

# Jobs for the tests stage.

.base-tests:
  parallel:
    matrix:
      - TOX_ENV_NAME:
        - py37-coverage
        - py38-coverage
        - py39-coverage

linux:
  extends:
    - .base-tests
    - .tests-linux

# windows:
#   extends:
#     - .base-tests
#     - .tests-windows
