include:
  - project: "gemseo/dev/ci-includes"
    file: "plugin.yml"

test:
  image: registry.gitlab.com/gemseo/dev/gemseo-petsc/multi-python-miniforge
  parallel:
    matrix:
      - TAG:
          - docker
        TOX_ENV_NAME:
          - py37-coverage
          - py38-coverage
          - py39-coverage
          - py310-coverage
