include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/test/plugin.yml"

variables:
  TEST_IMAGE:
    value: registry.gitlab.com/gemseo/dev/gemseo-petsc/multi-python-petsc

.test-tags:
  - saas-linux-small-amd64
